{"name": "test_vwo_login_negative", "status": "skipped", "statusDetails": {"message": "XFAIL reason: Failed TC\n\n_pytest.outcomes.XFailed: Failed TC", "trace": "setup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"c531098863e20b3572e81e78299ad8a8\")>\n\n    @allure.epic(\"VWO Login Test\")\n    @allure.feature(\"TC#0 - VWO App Negative Test\")\n    @pytest.mark.negative\n    def test_vwo_login_negative(setup):\n        try:\n            driver=setup\n            login_page=LoginPage(driver)\n            login_page.login_to_vwo(user=\"vijayatester16@gmail.com\",pwd=\"Wingify@1234\")\n            # time.sleep(2)\n>           error_msg_element=login_page.get_error_message_text()\n\ntests\\vwoLoginTests\\test_vwo_login.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntests\\pageObjects\\pom\\loginPage.py:51: in get_error_message_text\n    return self.get_error_message().text\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <tests.pageObjects.pom.loginPage.LoginPage object at 0x000001700A1A1D00>\n\n    def get_error_message(self):\n>       webdriver_wait(driver=self.driver, element_tuple=self.username)\nE       TypeError: webdriver_wait() missing 1 required positional argument: 'timeout'\n\ntests\\pageObjects\\pom\\loginPage.py:42: TypeError\n\nDuring handling of the above exception, another exception occurred:\n\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"c531098863e20b3572e81e78299ad8a8\")>\n\n    @allure.epic(\"VWO Login Test\")\n    @allure.feature(\"TC#0 - VWO App Negative Test\")\n    @pytest.mark.negative\n    def test_vwo_login_negative(setup):\n        try:\n            driver=setup\n            login_page=LoginPage(driver)\n            login_page.login_to_vwo(user=\"vijayatester16@gmail.com\",pwd=\"Wingify@1234\")\n            # time.sleep(2)\n            error_msg_element=login_page.get_error_message_text()\n            assert error_msg_element== \"Your email, password, IP address or location did not match\"\n    \n        except Exception as e:\n>           pytest.xfail(\"Failed TC\")\nE           _pytest.outcomes.XFailed: Failed TC\n\ntests\\vwoLoginTests\\test_vwo_login.py:33: XFailed"}, "start": 1741682074213, "stop": 1741682076341, "uuid": "002c2177-1d3c-4648-ade1-c443d88a7b6d", "historyId": "d768d3d769f5652f534d483ce8b8f9ed", "testCaseId": "d768d3d769f5652f534d483ce8b8f9ed", "fullName": "tests.vwoLoginTests.test_vwo_login#test_vwo_login_negative", "labels": [{"name": "feature", "value": "TC#0 - VWO App Negative Test"}, {"name": "epic", "value": "VWO Login Test"}, {"name": "tag", "value": "negative"}, {"name": "parentSuite", "value": "tests.vwoLoginTests"}, {"name": "suite", "value": "test_vwo_login"}, {"name": "host", "value": "LAPTOP-OLURE44J"}, {"name": "thread", "value": "9732-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.vwoLoginTests.test_vwo_login"}]}